%#function 
%#function MException.MException
%#function alexnet
%#function augmentedImageDatastore
%#function back2.jpg
%#function blacked_background
%#function bwareaopen
%#function bwlabel
%#function classify
%#function close
%#function colouredToGray_mex
%#function confusionmat
%#function dynamicprops.dynamicprops
%#function fitcecoc
%#function fullfile
%#function gabor
%#function gcp
%#function gpuArray
%#function gui_mainfcn
%#function guidata
%#function hold
%#function imageDatastore
%#function imagesc
%#function imbinarize
%#function imclearborder
%#function imgaborfilt
%#function imgaussfilt
%#function impixelinfo
%#function imread
%#function imresize
%#function imshow
%#function imsubtract
%#function ispc
%#function kmeans
%#function label2rgb
%#function main
%#function mat2gray
%#function matlab.mixin.CustomDisplay.CustomDisplay
%#function matlab.webcam.internal.Utility
%#function matlab.webcam.internal.webcamDesktop
%#function matlab.webcam.internal.webcamOnline
%#function mean
%#function medfilt2
%#function meshgrid
%#function num2str
%#function parfeval
%#function parpool
%#function pca
%#function predict
%#function regionprops
%#function res_train_classes
%#function resnet50
%#function rgb2gray
%#function std
%#function strcat
%#function title
%#function uistack
%#function webcam.webcam
